package com.feeye.test;

import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.junit.Test;

import java.util.List;

/**
 * @author xs
 * @description
 * @date 2019/9/12
 */
public class XmlTest {
    public static void main(String[] args) throws DocumentException {
        String xml =
                "<?xml version=\"1.0\" encoding=\"gb2312\"?>\n" +
                        "<JIT-Flight-Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"PN6339\" AirLine=\"PN\" FlightType=\"320\" Stime=\"06:35\" Etime=\"08:05\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T2,T2\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"W\" N=\"A\" D=\"0\" K=\"-0.400\" ID=\"sTOHMBjK3v4=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"arY2l+zG8DEKcryn+mA5Fg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"342266\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"J\" N=\"5\" D=\"0\" K=\"-0.400\" ID=\"akXEMKmZKKs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"7kDg3qk88WgHoUtt/GdmZg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"R\" N=\"A\" D=\"22\" P=\"370\" K=\"0.140\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.540\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"Z\" N=\"A\" D=\"24\" P=\"410\" K=\"0.087\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.487\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"29\" P=\"490\" K=\"0.008\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.408\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"A\" N=\"A\" D=\"32\" P=\"540\" K=\"-0.030\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.370\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"39\" P=\"660\" K=\"-0.097\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.303\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"P\" N=\"A\" D=\"35\" P=\"590\" K=\"-0.062\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.338\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"T\" N=\"A\" D=\"26\" P=\"440\" K=\"0.054\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.454\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"N\" N=\"A\" D=\"44\" P=\"740\" K=\"0.545\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.945\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"49\" P=\"830\" K=\"0.443\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.843\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"X\" N=\"A\" D=\"54\" P=\"910\" K=\"0.369\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.769\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"59\" P=\"1000\" K=\"0.300\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.700\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"65\" P=\"1100\" K=\"0.236\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.636\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"K\" N=\"A\" D=\"72\" P=\"1220\" K=\"0.173\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.573\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"80\" P=\"1350\" K=\"0.266\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mvnSYyHoiolqg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.666\" LeaveMoney=\"9\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"88\" P=\"1490\" K=\"0.204\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mvnSYyHoiolqg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.604\" LeaveMoney=\"9\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1690\" K=\"0.132\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mvnSYyHoiolqg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.532\" LeaveMoney=\"9\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"3U8361\" AirLine=\"3U\" FlightType=\"320\" Stime=\"07:30\" Etime=\"09:05\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T2,T1\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"W1\" N=\"5\" D=\"0\" K=\"0.000\" ID=\"BWN1BvKdD7o=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"5fiPooxfb3dUG1eTuwEQ7Q==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"234287\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"W\" N=\"5\" D=\"0\" K=\"0.000\" ID=\"akXEMKmZKKs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"eHf1BlOrsAm50+c7f2PN2g==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"R\" N=\"A\" D=\"40\" P=\"560\" K=\"3.964\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"AStbg6l1x2YrrfHbYI4kjQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"4.464\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"45\" P=\"630\" K=\"3.468\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"AStbg6l1x2YrrfHbYI4kjQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"3.968\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"E\" N=\"A\" D=\"50\" P=\"700\" K=\"3.071\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"2.571\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"60\" P=\"840\" K=\"2.642\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"2.142\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"S\" N=\"A\" D=\"65\" P=\"910\" K=\"2.478\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.978\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"G\" N=\"A\" D=\"70\" P=\"980\" K=\"2.336\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.836\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"80\" P=\"1120\" K=\"2.732\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"2.232\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"T\" N=\"A\" D=\"90\" P=\"1260\" K=\"2.484\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.984\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1400\" K=\"2.285\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.785\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"A\" N=\"2\" D=\"100\" P=\"1400\" K=\"2.285\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"F\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.785\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"P\" N=\"8\" D=\"0\" K=\"0.200\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"0kLtP+i3d8YnE+cfJF7wvQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"J\" N=\"2\" D=\"130\" P=\"1820\" K=\"2.313\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"0kLtP+i3d8ZR8zMJLWVWkw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.813\" LeaveMoney=\"33\" />\n" +
                        "    <Cabin C=\"I\" N=\"2\" D=\"200\" P=\"2800\" K=\"1.678\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"0kLtP+i3d8ZR8zMJLWVWkw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.178\" LeaveMoney=\"33\" />\n" +
                        "    <Cabin C=\"C\" N=\"8\" D=\"300\" P=\"4200\" K=\"1.619\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"KsOcD8DNeMEZhRTuhxKVMw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.119\" LeaveMoney=\"47\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"MF8420\" AirLine=\"MF\" FlightType=\"738\" Stime=\"08:00\" Etime=\"09:35\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T3,--\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"0\" K=\"-0.200\" ID=\"OXFSfGGAnk4=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"VJZs0p63qsy3Za18Fls/rQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"898829\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"R\" N=\"A\" D=\"40\" P=\"560\" K=\"0.692\" ID=\"OXFSfGGAnk4=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"VJZs0p63qsy3Za18Fls/rQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"898829\" LeaveDiscount=\"0.892\" LeaveMoney=\"5\" />\n" +
                        "    <Cabin C=\"T\" N=\"A\" D=\"45\" P=\"630\" K=\"2.557\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"yUqdJfPypdUDOYMIlaLzbw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"2.857\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"51\" P=\"710\" K=\"2.235\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"yUqdJfPypdUDOYMIlaLzbw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"2.535\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"61\" P=\"850\" K=\"1.817\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"yUqdJfPypdUDOYMIlaLzbw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"2.117\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"N\" N=\"A\" D=\"66\" P=\"920\" K=\"1.656\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"yUqdJfPypdUDOYMIlaLzbw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"1.956\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"K\" N=\"A\" D=\"71\" P=\"990\" K=\"1.518\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"yUqdJfPypdUDOYMIlaLzbw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"1.818\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"76\" P=\"1060\" K=\"1.398\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"yUqdJfPypdUDOYMIlaLzbw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"1.698\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"81\" P=\"1130\" K=\"1.812\" ID=\"705ozDOLmXI=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"换编码出票，出票后请核对新编码里的证件号以及客人航班信息\" RID=\"arzteJoHSYSiPwqyBhK1VA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"463948\" LeaveDiscount=\"2.212\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"91\" P=\"1270\" K=\"1.568\" ID=\"705ozDOLmXI=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"换编码出票，出票后请核对新编码里的证件号以及客人航班信息\" RID=\"arzteJoHSYSiPwqyBhK1VA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"463948\" LeaveDiscount=\"1.968\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"99\" P=\"1390\" K=\"1.398\" ID=\"705ozDOLmXI=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"换编码出票，出票后请核对新编码里的证件号以及客人航班信息\" RID=\"arzteJoHSYSiPwqyBhK1VA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"463948\" LeaveDiscount=\"1.798\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1400\" K=\"1.385\" ID=\"705ozDOLmXI=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"换编码出票，出票后请核对新编码里的证件号以及客人航班信息\" RID=\"arzteJoHSYSiPwqyBhK1VA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"463948\" LeaveDiscount=\"1.785\" LeaveMoney=\"25\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"CZ8153\" AirLine=\"CZ\" FlightType=\"32H\" Stime=\"08:05\" Etime=\"09:30\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T3,T2\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"S\" N=\"4\" D=\"0\" K=\"-0.300\" ID=\"Ivkkzka1+Mo=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"ZSFUjMGgk3I4MEGhweNvdQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"Z\" N=\"A\" D=\"40\" P=\"560\" K=\"1.585\" ID=\"Ivkkzka1+Mo=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.785\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"46\" P=\"640\" K=\"1.362\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.562\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"E\" N=\"A\" D=\"51\" P=\"710\" K=\"1.208\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.408\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"61\" P=\"850\" K=\"0.976\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.176\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"A\" N=\"A\" D=\"66\" P=\"920\" K=\"0.886\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.086\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"71\" P=\"990\" K=\"0.810\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.010\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"76\" P=\"1060\" K=\"0.743\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"0.943\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"81\" P=\"1130\" K=\"1.027\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.327\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"91\" P=\"1270\" K=\"0.881\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.181\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1400\" K=\"0.771\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.071\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"W\" N=\"A\" D=\"100\" P=\"1400\" K=\"0.771\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.071\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"D\" N=\"1\" D=\"101\" P=\"1410\" K=\"1.118\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kMAWN++3elZQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.418\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"C\" N=\"2\" D=\"180\" P=\"2520\" K=\"0.493\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kMAWN++3elZQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"0.793\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"J\" N=\"3\" D=\"230\" P=\"3220\" K=\"0.942\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"yB28LdwTy8bdDgTByDcWBg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.242\" LeaveMoney=\"40\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"3U8951\" AirLine=\"3U\" FlightType=\"32Z\" Stime=\"13:00\" Etime=\"14:20\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T2,T1\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"E\" N=\"1\" D=\"50\" P=\"700\" K=\"3.071\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"2.571\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"L\" N=\"2\" D=\"60\" P=\"840\" K=\"2.642\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"2.142\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"G\" N=\"A\" D=\"70\" P=\"980\" K=\"2.336\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7XP5JFcGHkcEeov6ciD2wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.836\" LeaveMoney=\"18\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"80\" P=\"1120\" K=\"2.732\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"2.232\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"T\" N=\"A\" D=\"90\" P=\"1260\" K=\"2.484\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.984\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1400\" K=\"2.285\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.785\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"A\" N=\"4\" D=\"100\" P=\"1400\" K=\"2.285\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"F\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"AcSF3Z9abqhFagCmV0WRuQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.785\" LeaveMoney=\"25\" />\n" +
                        "    <Cabin C=\"P\" N=\"A\" D=\"0\" K=\"0.200\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"0kLtP+i3d8YnE+cfJF7wvQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"J\" N=\"4\" D=\"130\" P=\"1820\" K=\"2.313\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"0kLtP+i3d8ZR8zMJLWVWkw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.813\" LeaveMoney=\"33\" />\n" +
                        "    <Cabin C=\"I\" N=\"4\" D=\"200\" P=\"2800\" K=\"1.678\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"0kLtP+i3d8ZR8zMJLWVWkw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.178\" LeaveMoney=\"33\" />\n" +
                        "    <Cabin C=\"C\" N=\"A\" D=\"300\" P=\"4200\" K=\"1.619\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"KsOcD8DNeMEZhRTuhxKVMw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.119\" LeaveMoney=\"47\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"PN6231\" AirLine=\"PN\" FlightType=\"320\" Stime=\"16:05\" Etime=\"17:35\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T2,T2\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"W\" N=\"A\" D=\"0\" K=\"-0.400\" ID=\"sTOHMBjK3v4=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"arY2l+zG8DEKcryn+mA5Fg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"342266\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"J\" N=\"6\" D=\"0\" K=\"-0.400\" ID=\"akXEMKmZKKs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"7kDg3qk88WgHoUtt/GdmZg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"39\" P=\"660\" K=\"-0.097\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.303\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"P\" N=\"A\" D=\"35\" P=\"590\" K=\"-0.062\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7msWGKIhPnHO8w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.338\" LeaveMoney=\"2\" />\n" +
                        "    <Cabin C=\"N\" N=\"A\" D=\"44\" P=\"740\" K=\"0.545\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.945\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"49\" P=\"830\" K=\"0.443\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.843\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"X\" N=\"A\" D=\"54\" P=\"910\" K=\"0.369\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.769\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"59\" P=\"1000\" K=\"0.300\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.700\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"65\" P=\"1100\" K=\"0.236\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.636\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"K\" N=\"A\" D=\"72\" P=\"1220\" K=\"0.173\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mt6hZMAWT4pug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.573\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"80\" P=\"1350\" K=\"0.266\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mvnSYyHoiolqg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.666\" LeaveMoney=\"9\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"88\" P=\"1490\" K=\"0.204\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mvnSYyHoiolqg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.604\" LeaveMoney=\"9\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1690\" K=\"0.132\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票\" RID=\"hX76XIXv7mvnSYyHoiolqg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.532\" LeaveMoney=\"9\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"CA4597\" AirLine=\"CA\" FlightType=\"73N\" Stime=\"20:05\" Etime=\"21:30\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T3,T1\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"S\" N=\"4\" D=\"45\" P=\"560\" K=\"1.985\" ID=\"KiqcBKyZ+n8=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"OTS3iILb9JbP7DKYHso9Dg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.785\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"T\" N=\"A\" D=\"0\" K=\"0.000\" ID=\"3Qk6ZPc5zRs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"签转、换开、跨月改期，收回代理费\" RID=\"LrX7ExHPkys2I7RmrJsOSQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"904250\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"N\" N=\"3\" D=\"0\" K=\"0.000\" ID=\"3Qk6ZPc5zRs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"签转、换开、跨月改期，收回代理费\" RID=\"LrX7ExHPkys2I7RmrJsOSQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"904250\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"W\" N=\"A\" D=\"51\" P=\"640\" K=\"1.762\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"OTS3iILb9JbP7DKYHso9Dg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.562\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"62\" P=\"780\" K=\"1.482\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"tA4+P5tSJ2rT8/AvrbtUvg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.282\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"72\" P=\"900\" K=\"1.311\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"tA4+P5tSJ2rT8/AvrbtUvg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.111\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"77\" P=\"960\" K=\"1.241\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"tA4+P5tSJ2rT8/AvrbtUvg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.041\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"82\" P=\"1030\" K=\"1.656\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"5U2UpInJXr16OXXs2YV1PQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.456\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"M1\" N=\"A\" D=\"87\" P=\"1090\" K=\"1.576\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"5U2UpInJXr16OXXs2YV1PQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.376\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"90\" P=\"1130\" K=\"1.527\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"5U2UpInJXr16OXXs2YV1PQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.327\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"92\" P=\"1150\" K=\"1.504\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"5U2UpInJXr16OXXs2YV1PQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.304\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1250\" K=\"1.400\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"5U2UpInJXr16OXXs2YV1PQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.200\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"R\" N=\"2\" D=\"100\" P=\"1250\" K=\"1.420\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7tucG4f/m71FFdidfpD/Gg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.520\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"Z\" N=\"2\" D=\"130\" P=\"1630\" K=\"1.065\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7tucG4f/m71FFdidfpD/Gg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.165\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"D\" N=\"2\" D=\"150\" P=\"1880\" K=\"0.910\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7tucG4f/m71FFdidfpD/Gg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.010\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"C\" N=\"2\" D=\"180\" P=\"2250\" K=\"0.744\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7tucG4f/m71FFdidfpD/Gg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"0.844\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"J\" N=\"8\" D=\"200\" P=\"2500\" K=\"1.420\" ID=\"CvTMW2r8cXQ=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码，改签需收回代理费\" RID=\"7tucG4f/m71jdlsWyn72lw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"18485\" LeaveDiscount=\"1.520\" LeaveMoney=\"38\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"CZ8053\" AirLine=\"CZ\" FlightType=\"320\" Stime=\"20:35\" Etime=\"21:55\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T3,T2\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"S\" N=\"5\" D=\"0\" K=\"-0.300\" ID=\"Ivkkzka1+Mo=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"ZSFUjMGgk3I4MEGhweNvdQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"Z\" N=\"A\" D=\"40\" P=\"560\" K=\"1.585\" ID=\"Ivkkzka1+Mo=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.785\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"46\" P=\"640\" K=\"1.362\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.562\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"E\" N=\"A\" D=\"51\" P=\"710\" K=\"1.208\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.408\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"61\" P=\"850\" K=\"0.976\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.176\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"A\" N=\"A\" D=\"66\" P=\"920\" K=\"0.886\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.086\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"71\" P=\"990\" K=\"0.810\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.010\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"76\" P=\"1060\" K=\"0.743\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kVhFc/njFqQg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"0.943\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"81\" P=\"1130\" K=\"1.027\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.327\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"91\" P=\"1270\" K=\"0.881\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.181\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1400\" K=\"0.771\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.071\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"W\" N=\"A\" D=\"100\" P=\"1400\" K=\"0.771\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6mibmt3A2ZUsw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.071\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"I\" N=\"2\" D=\"84\" P=\"1180\" K=\"1.394\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kMAWN++3elZQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.694\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"D\" N=\"3\" D=\"101\" P=\"1410\" K=\"1.118\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kMAWN++3elZQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.418\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"C\" N=\"4\" D=\"180\" P=\"2520\" K=\"0.493\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"TkGTxnV3Z6kMAWN++3elZQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"0.793\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"J\" N=\"8\" D=\"230\" P=\"3220\" K=\"0.942\" ID=\"Ivkkzka1+Mo=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"yB28LdwTy8bdDgTByDcWBg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"570887\" LeaveDiscount=\"1.242\" LeaveMoney=\"40\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"HU7410\" AirLine=\"HU\" FlightType=\"738\" Stime=\"23:00\" Etime=\"00:20\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T3,T2\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"0\" K=\"-0.400\" ID=\"akXEMKmZKKs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"82DcLQhUloQeDnxa/K68Wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"A\" N=\"A\" D=\"36\" P=\"550\" K=\"0.327\" ID=\"akXEMKmZKKs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"82DcLQhUloQeDnxa/K68Wg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0.727\" LeaveMoney=\"4\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"0\" K=\"-0.400\" ID=\"akXEMKmZKKs=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"82DcLQhUloQ/0aDhjbNIFA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"N\" N=\"A\" D=\"42\" P=\"650\" K=\"1.792\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"+eQY9liqNwduAe6bYFe0Xg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.692\" LeaveMoney=\"11\" />\n" +
                        "    <Cabin C=\"V\" N=\"A\" D=\"48\" P=\"740\" K=\"1.586\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"+eQY9liqNwduAe6bYFe0Xg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.486\" LeaveMoney=\"11\" />\n" +
                        "    <Cabin C=\"X\" N=\"A\" D=\"54\" P=\"830\" K=\"1.425\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"+eQY9liqNwduAe6bYFe0Xg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.325\" LeaveMoney=\"11\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"60\" P=\"920\" K=\"1.086\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"UbVKk2y4ov7xKKlZBImJgg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.086\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"68\" P=\"1050\" K=\"0.952\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"UbVKk2y4ov7xKKlZBImJgg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"0.952\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"K\" N=\"A\" D=\"76\" P=\"1170\" K=\"0.854\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需换编码出票，签转、换开、跨月改期，收回代理费.\" RID=\"UbVKk2y4ov7xKKlZBImJgg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"0.854\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"84\" P=\"1290\" K=\"0.762\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"+GmOuFWBSKaSyz25x6yJCQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.162\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"92\" P=\"1420\" K=\"0.656\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"+GmOuFWBSKaSyz25x6yJCQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.056\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1540\" K=\"0.574\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"+GmOuFWBSKaSyz25x6yJCQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"0.974\" LeaveMoney=\"15\" />\n" +
                        "    <Cabin C=\"R\" N=\"2\" D=\"0\" K=\"-0.400\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"82DcLQhUloSiKz7xJWbS9w==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"I\" N=\"4\" D=\"110\" P=\"1690\" K=\"0.724\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"vR64hFC7ZbgRoezWHrY6uQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"1.124\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"Z\" N=\"6\" D=\"150\" P=\"2310\" K=\"0.422\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"vR64hFC7ZbgRoezWHrY6uQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"0.822\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"D\" N=\"7\" D=\"220\" P=\"3390\" K=\"0.160\" ID=\"KiqcBKyZ+n8=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"需要换编码出票，改签即收回代理费\" RID=\"vR64hFC7ZbgRoezWHrY6uQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"24975\" LeaveDiscount=\"0.560\" LeaveMoney=\"19\" />\n" +
                        "    <Cabin C=\"C\" N=\"8\" D=\"300\" P=\"4620\" K=\"0.660\" ID=\"akXEMKmZKKs=\" T=\"0\" L=\"C\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"eHf1BlOrsAnhTAGBUQx0QA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"854288\" LeaveDiscount=\"1.060\" LeaveMoney=\"49\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"BK2738\" AirLine=\"BK\" FlightType=\"73E\" Stime=\"23:20\" Etime=\"00:40\" Stop=\"0\" EPiao=\"E\" Tax=\"50\" AirTerminal=\"T3,T1\" AirTax=\"50\" Fees=\"0\">\n" +
                        "    <Cabin C=\"O3\" N=\"A\" D=\"26\" P=\"400\" K=\"-0.300\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"M4Dm0s4eSQyEUYBr1qqdtg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"O\" N=\"A\" D=\"33\" P=\"510\" K=\"1.072\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcAl1nVD+82oCw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.372\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"D\" N=\"5\" D=\"38\" P=\"590\" K=\"0.886\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcAl1nVD+82oCw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.186\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"T\" N=\"7\" D=\"43\" P=\"660\" K=\"0.760\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"GiyefoRPLdq5VGmZyqJzrA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.060\" LeaveMoney=\"7\" />\n" +
                        "    <Cabin C=\"U\" N=\"A\" D=\"48\" P=\"740\" K=\"1.321\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcDVaQjX7VhDHw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.621\" LeaveMoney=\"12\" />\n" +
                        "    <Cabin C=\"E\" N=\"A\" D=\"53\" P=\"820\" K=\"1.163\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcDVaQjX7VhDHw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.463\" LeaveMoney=\"12\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"63\" P=\"970\" K=\"0.937\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcDVaQjX7VhDHw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.237\" LeaveMoney=\"12\" />\n" +
                        "    <Cabin C=\"N\" N=\"A\" D=\"68\" P=\"1050\" K=\"1.223\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcASpTwnpIV9pw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.523\" LeaveMoney=\"16\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"73\" P=\"1120\" K=\"1.128\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcASpTwnpIV9pw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.428\" LeaveMoney=\"16\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"78\" P=\"1200\" K=\"1.033\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcASpTwnpIV9pw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.333\" LeaveMoney=\"16\" />\n" +
                        "    <Cabin C=\"K\" N=\"A\" D=\"83\" P=\"1280\" K=\"0.950\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcASpTwnpIV9pw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.250\" LeaveMoney=\"16\" />\n" +
                        "    <Cabin C=\"B\" N=\"A\" D=\"93\" P=\"1430\" K=\"1.098\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcD4CIvDPO1uCg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.398\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1540\" K=\"0.998\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"MA/qK1lRKcD4CIvDPO1uCg==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.298\" LeaveMoney=\"20\" />\n" +
                        "  </Response>\n" +
                        "  <Response Sdate=\"2019-10-14\" Scity=\"CKG\" Ecity=\"CSX\" FlightNo=\"G52763\" AirLine=\"G5\" FlightType=\"CR9\" Stime=\"14:50\" Etime=\"17:50\" Stop=\"1\" EPiao=\"E\" Tax=\"0\" AirTerminal=\"2A,T2\" AirTax=\"0\" Fees=\"0\">\n" +
                        "    <Cabin C=\"Z\" N=\"3\" D=\"0\" K=\"-0.300\" ID=\"Ys8lWZaKmjU=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"7+RILdJ4l+A59pkNeiwfiA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"833048\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"E\" N=\"A\" D=\"38\" P=\"590\" K=\"0.547\" ID=\"rD9kUVAlWuE=\" T=\"1\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqKOHkn0nEWcw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.847\" LeaveMoney=\"5\" />\n" +
                        "    <Cabin C=\"Q\" N=\"A\" D=\"44\" P=\"680\" K=\"0.435\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqKOHkn0nEWcw==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.735\" LeaveMoney=\"5\" />\n" +
                        "    <Cabin C=\"L\" N=\"A\" D=\"51\" P=\"790\" K=\"0.965\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqN3086ZdU5Ug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.265\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"S\" N=\"A\" D=\"58\" P=\"890\" K=\"0.823\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqN3086ZdU5Ug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.123\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"G\" N=\"A\" D=\"64\" P=\"990\" K=\"0.710\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqN3086ZdU5Ug==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.010\" LeaveMoney=\"10\" />\n" +
                        "    <Cabin C=\"M\" N=\"A\" D=\"71\" P=\"1090\" K=\"1.534\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqTNkWvJxZPpQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.834\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"H\" N=\"A\" D=\"78\" P=\"1200\" K=\"1.366\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqTNkWvJxZPpQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.666\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"T\" N=\"A\" D=\"88\" P=\"1360\" K=\"1.170\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqTNkWvJxZPpQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.470\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"Y\" N=\"A\" D=\"100\" P=\"1540\" K=\"0.998\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqTNkWvJxZPpQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.298\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"I\" N=\"4\" D=\"0\" K=\"-0.300\" ID=\"Ys8lWZaKmjU=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"7+RILdJ4l+A59pkNeiwfiA==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"833048\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"B\" N=\"4\" D=\"100\" P=\"1540\" K=\"0.998\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"Y\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"V/hN4Yy5OWqTNkWvJxZPpQ==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"1.298\" LeaveMoney=\"20\" />\n" +
                        "    <Cabin C=\"A\" N=\"3\" D=\"0\" K=\"-0.300\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"F\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"jshjQVhd/T3xKjr8ca2O4A==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0\" LeaveMoney=\"0\" />\n" +
                        "    <Cabin C=\"F\" N=\"3\" D=\"300\" P=\"4620\" K=\"0.241\" ID=\"rD9kUVAlWuE=\" T=\"0\" L=\"F\" XF=\"0\" PI=\"0\" RT=\"0\" RM=\"\" RID=\"jshjQVhd/T3xKjr8ca2O4A==\" OfficeNum=\"\" Change=\"\" Return=\"\" ProviderId=\"1662\" LeaveDiscount=\"0.541\" LeaveMoney=\"25\" />\n" +
                        "  </Response>\n" +
                        "</JIT-Flight-Response>";

        Document document = DocumentHelper.parseText(xml);
        Element rootElement = document.getRootElement();
        List <Element> elements = rootElement.elements();
        for (int i = 0; i < elements.size(); i++) {
            //匹配航班
            if("3U8361".equals(elements.get(i).attributeValue("FlightNo"))) {
                System.out.println(elements.get(i).attributeValue("FlightNo"));
                List <Element> cabinList = elements.get(i).elements("Cabin");
                for (int j = 0; j <cabinList.size(); j++) {
                    String p = cabinList.get(j).attributeValue("P");

                }
            }

            String Sdate = elements.get(i).attributeValue("Sdate");
            String FlightNo = elements.get(i).attributeValue("FlightNo");
            String c = elements.get(i).element("Cabin").attributeValue("C");
            String K = elements.get(i).element("Cabin").attributeValue("K");
            String Scity = elements.get(i).attributeValue("Scity");
        }
    }


    @Test
    public void a() throws DocumentException {
        String back = "<?xml version=\"1.0\" encoding=\"gb2312\"?>\n" +
                "<response>\n" +
                "\t<status>0</status>\n" +
                "\t<errorCode>1</errorCode>\n" +
                "\t<errorMessage>test</errorMessage>\n" +
                "\t<orderNo>123</orderNo>\n" +
                "\t<orderStatus>112</orderStatus>\n" +
                "</response>\n";
        Document document = DocumentHelper.parseText(back);
        Element root = document.getRootElement();
        List<Element> childElements = root.elements();
        String status = root.elementText("status");
                // root.element("status").getText();
        String errorMsg = root.element("errorMessage").getText();
    }
}
